# Travis CI Configuration File

language: php

sudo: false

matrix:
  include:
  - php: 7.0
    env: WP_TRAVISCI=travis:phpvalidate
  - php: 7.0
    env: WP_TRAVISCI=travis:codecoverage
  - php: 7.0
    env: WP_TRAVISCI=travis:jshint
  - php: 7.0
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 7.0
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=latest
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=latest
  - php: 5.5
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.4
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: hhvm
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  apt: true
  bundler: true
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules

before_install:
  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

  - cd $TRAVIS_BUILD_DIR
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install
  - node --version
  - npm --version
  - grunt --version
  - composer self-update

# Clones WordPress and configures our testing environment.
before_script:
  - composer install --no-interaction
  - |
     if [[ "$WP_TRAVISCI" == "travis:checktextdomain" ]] ; then
       grunt checktextdomain
     fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpvalidate" ]] ; then
      grunt checktextdomain
     vendor/bin/phpmd classes text codesize,naming,unusedcode
     vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml classes
    fi
  - |
     if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
       phpunit --coverage-clover build/logs/clover.xml
     fi
  - |
     if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
       grunt jshint
     fi
  - phpunit

after_script:
  # Push coverage off to Codecov
- |
  if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  slack:
    rooms:
      secure: DRNZFDsqyLVatedaAvAcnO5D9Yfv6QB9JhsLCSP3mcVqH5Df25NxwMn9hAygK60TI715TxEw087vry3j3C2MpPcMrhsGAQjDyIBmPogZ8HUyLPE+ud8qG8snXv5yVt9EXnVWUtkeYu+XWndRHEGUNdicJ8Eu/0FtMh5GthlUAAFe73R7MWo0BdANamV5buQ5SQgWa4ZJRcrWnYAX9d4f33t1/Mbdmo0CSw3OK97J9Q0leudd0GkYqmhd4F5i4JM5FZwiWkzEJl6ApifezDQz+pJDIiFWTJMg8eCghLKnPzsF3j/7ZCiHfksRAnMU/X/OB5Su5vgglnoUBvf15sU0xIPdy7SmKDS+QsFzdP37PtJ+iKGmxormDh7YutFBigFX/oQE3NVKBYm/cZtzIihBQuYhbAMS4OEA+G6vgxCrN1gF0kHH8FDownV2kWtKcwtRhEaBnFcH4U0t2RGfXi15CQs2Xk/9Ps7kfMnC2apl7UdXqU4prOAR8FNZM3LSX9Wb/c7IXSDdYcXPDX8QnPFvwXe8Q9frXN/KuFIhrcCBSrrS7LmBlc1qs/6QZ5EDKV8mjwdvXNoK+XXn9LShvYHtKmF394iiPMBttYv5CJWi2723wnwljji5/L2kboMFZ41LDAnAFjLnXArRXi9yKhzjhH9Rd35zuok2yU+vgL3FDuI=
    on_start: never
    on_failure: always
    on_success: change