# Travis CI Configuration File

language: php

sudo: false

matrix:
  include:
  - php: 7.0
    env: WP_TRAVISCI=travis:phpvalidate
  - php: 7.0
    env: WP_TRAVISCI=travis:codecoverage
  - php: 7.0
    env: WP_TRAVISCI=travis:jshint
  - php: 7.0
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 7.0
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=latest
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=latest
  - php: 5.5
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.4
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.3
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 5.2
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: hhvm
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  apt: true
  bundler: true
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules

before_install:
  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

  - cd $TRAVIS_BUILD_DIR
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install
  - node --version
  - npm --version
  - grunt --version
  - composer self-update

# Clones WordPress and configures our testing environment.
before_script:
  - composer install --no-interaction
  - |
     if [[ "$WP_TRAVISCI" == "travis:checktextdomain" ]] ; then
       grunt checktextdomain
     fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpvalidate" ]] ; then
      grunt checktextdomain
     vendor/bin/phpmd classes text codesize,naming,unusedcode
     vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml classes
    fi
  - |
     if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
       phpunit --coverage-clover build/logs/clover.xml
     fi
  - |
     if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
       grunt jshint
     fi
  - phpunit

after_script:
  # Push coverage off to Codecov
- |
  if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
    bash <(curl -s https://codecov.io/bash)
    vendor/bin/test-reporter
  fi

notifications:
  slack:
    rooms:
      secure: dVNKRk+6ptcuFn6SiT5SD0Rij5to3z3CETgNMAN1bdrczvYcMgyhZrW/51ihlGpMfdB45HuKI42tyLeNPOy6eMUg2weqonW5K+iVWw26toaVN5SV1hg7517A6f3GY5pLLCqV8uH5TKCvinGpPophf1upoHdTwnbAlQrlE2wPLg6oTsifqL73+mq5ieDizbu+1YJe6OHGhod7X64W8lB71QSN+6IXAbbqF1B7eCajzfa3BhAFRKSA7kCQwXuTNMCGhNPWeZBb8ljlcuTit9zFApmrDuI/JFK+ksDydhctygXrogZl8lj4Wg086vU4vphEPp+LJwU7T84J0shcxqVBI8/dW67ucZDP8Ghd5frj821EM41mnHz628nc1EFgIxgIdDr4bTQVh++bE5rnRMsi814p5tqu9gD1agbeXaQoZvqKofjamgLjV0JgEdsjl8L2+sKkgnq5KtZ0pZ919+G0xuUPlcAiuCa4SVLMJS64nxAYKEPIvlc1MU5Ue2yPCQBYD1hD552L0AyimEw9QExB3tBJm2XhwC6WHCi6m+T9E6+8n46a/he0HVAh89gLUpm3RHQc5i2THO7QLjIia4qG1pN4pQ7b+4lwCfuYzoSrDwxJ2BO8ha0tzLmcUl7EntxahmELQc48E/fxWgg374vOBTdqWVSrod4YvEdrcr1YKyQ=
    on_start: never
    on_failure: always
    on_success: change